apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udacapstone-frontend
  name: udacapstone-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacapstone-frontend
  template:
    metadata:
      labels:
        app: udacapstone-frontend
        role: RollingUpdate
    spec:
      containers:
        - image: yangnguyen1993/udacity-capstone-image:${CIRCLE_WORKFLOW_ID:0:7}
          name: udacity-capstone-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacapstone-frontend
  name: udacapstone-frontend
spec:
  type: LoadBalancer
  selector:
    app: udacapstone-frontend
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      protocol: TCP
