apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udacapstone-frontend
  name: udacapstone-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udacapstone-frontend
  template:
    metadata:
      labels:
        service: udacapstone-frontend
        api: external
    spec:
      containers:
        - image: yangnguyen1993/udacity-capstone-image:${CIRCLE_WORKFLOW_ID:0:7}
          name: udacity-capstone-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always