apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacapstone-frontend
  name: udacapstone-frontend
spec:
  type: LoadBalancer
  selector:
    app: udacapstone-frontend
  ports:
    - name: "8181"
      port: 8181
      targetPort: 80
      protocol: TCP