apiVersion: v1
kind: Service
metadata:
  labels:
    service: udacapstone-frontend
  name: udacapstone-frontend
spec:
  type: NodePort
  ports:
    - name: "8181"
      port: 8181
      targetPort: 80
      protocol: TCP
  selector:
    service: udacapstone-frontend